# Generated by Django 5.1 on 2024-08-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
