# Generated by Django 5.1 on 2024-08-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_no', models.IntegerField(max_length=8)),
                ('serial_number', models.CharField(max_length=20, unique=True)),
                ('id_name', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=30)),
                ('district_of_birth', models.CharField(max_length=50)),
                ('date_of_issue', models.CharField(max_length=20)),
                ('id_image', models.FileField(upload_to='id_image')),
                ('id_status', models.CharField(max_length=20)),
            ],
        ),
    ]
