# Generated by Django 5.1 on 2024-09-27 17:40

import django.db.models.deletion
import django.utils.timezone
import id_finder.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_finder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ID',
            fields=[
                ('primary_key', models.AutoField(default=1, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_name', models.CharField(max_length=255)),
                ('sn', models.CharField(max_length=12)),
                ('id_no', models.CharField(max_length=8, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('district_of_birth', models.CharField(max_length=255)),
                ('date_of_issue', models.DateField()),
                ('front_image', models.ImageField(upload_to=id_finder.models.id_image_upload_path)),
                ('back_image', models.ImageField(upload_to=id_finder.models.id_image_upload_path)),
                ('id_status', models.CharField(choices=[('Found', 'Found'), ('Claimed', 'Claimed')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ids_found', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='IDModel',
        ),
    ]
