# Generated by Django 5.1 on 2024-09-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_finder', '0002_id_delete_idmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='id',
            name='id_image',
        ),
        migrations.AddField(
            model_name='id',
            name='back_image',
            field=models.ImageField(default='id_images/back/default.jpg', upload_to='id_images/back/'),
        ),
        migrations.AddField(
            model_name='id',
            name='front_image',
            field=models.ImageField(default='id_images/front/default.jpg', upload_to='id_images/front/'),
        ),
    ]
