# Generated by Django 5.1 on 2024-09-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_finder', '0004_alter_id_back_image_alter_id_front_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='id_no',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
