# Generated by Django 5.1 on 2024-09-27 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_finder', '0004_idclaim_date_of_birth_idclaim_district_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idclaim',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 28, 0, 38, 29, 261688)),
        ),
    ]
