# Generated by Django 5.1 on 2024-09-27 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_finder', '0005_alter_idclaim_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idclaim',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 28, 1, 53, 23, 884882)),
        ),
    ]
