# Generated by Django 5.1 on 2024-09-17 07:57

import id_finder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_finder', '0006_alter_id_sn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='back_image',
            field=models.ImageField(upload_to=id_finder.models.id_image_upload_path),
        ),
        migrations.AlterField(
            model_name='id',
            name='front_image',
            field=models.ImageField(upload_to=id_finder.models.id_image_upload_path),
        ),
    ]
