# Generated by Django 5.1 on 2024-09-29 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_finder', '0006_alter_idclaim_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='idclaim',
            name='id_no',
            field=models.CharField(default='75835858', max_length=8),
        ),
        migrations.AlterField(
            model_name='idclaim',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 29, 10, 42, 35, 403727)),
        ),
    ]
