# Generated by Django 5.1 on 2024-09-30 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_finder', '0007_idclaim_id_no_alter_idclaim_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='idclaim',
            name='image_match',
            field=models.CharField(default='70', max_length=3),
        ),
        migrations.AlterField(
            model_name='idclaim',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 30, 12, 47, 51, 669329)),
        ),
    ]
