# Generated by Django 5.1 on 2024-09-25 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_finder', '0007_alter_id_back_image_alter_id_front_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='id',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
