# Generated by Django 5.1 on 2024-09-30 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_finder', '0008_idclaim_image_match_alter_idclaim_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='id',
            name='primary_key',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='idclaim',
            name='date_of_birth',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 30, 13, 11, 54, 259897)),
        ),
    ]
