# Generated by Django 5.1 on 2024-09-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_finder', '0008_id_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='id',
            name='id',
        ),
        migrations.AddField(
            model_name='id',
            name='primary_key',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
