# Generated by Django 5.1 on 2024-09-23 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('message', models.TextField()),
                ('user', models.TextField(default='anonymous')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.AddField(
            model_name='chats',
            name='room',
            field=models.CharField(default='common room', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.chats'),
        ),
    ]
